Implement a python program to compute  Central Tendency Measures: Mean, Median, Mode  Measure of Dispersion: Variance, Standard Deviation (Using Possum Dataset)

In [12]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from scipy import stats

import pandas as pd
import numpy as np
from scipy import stats

In [2]:
data = pd.read_csv('./data/possum.csv')
data.head()

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0

In [3]:
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   case      104 non-null    int64
 1   site      104 non-null    int64
 2   Pop       104 non-null    object
 3   sex       104 non-null    object
 4   age       102 non-null    float64
 5   hdlngth   104 non-null    float64
 6   skullw    104 non-null    float64
 7   totlngth  104 non-null    float64
 8   taill     104 non-null    float64
 9   footlgth  103 non-null    float64
 10  earconch  104 non-null    float64
 11  eye       104 non-null    float64
 12  chest     104 non-null    float64
 13  belly     104 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 11.5+ KB

In [4]:
df = df.drop(['Pop'], axis=1)
df['sex'] = pd.get_dummies(df['sex'], drop_first=True)

In [8]:
mean_values = df.mean()
median_values = df.median()
mode_values = df.mode().iloc[0]

In [10]:
variance_values = df.var()
std_dev_values = df.std()

In [11]:
print("Mean:\n", mean_values)
print("\nMedian:\n", median_values)
print("\nMode:\n", mode_values)
print("\nVariance:\n", variance_values)
print("\nStandard Deviation:\n", std_dev_values)

Mean:
 case        52.500000
site         3.625000
sex          0.586538
age          3.833333
hdlngth     92.602885
skullw      56.883654
totlngth    87.088462
taill       37.009615
footlgth    68.459223
earconch    48.130769
eye         15.046154
chest       27.000000
belly       32.586538
dtype: float64

Median:
 case        52.50
site         3.00
sex          1.00
age          3.00
hdlngth     92.80
skullw      56.35
totlngth    88.00
taill       37.00
footlgth    68.00
earconch    46.80
eye         14.90
chest       27.00
belly       32.50
dtype: float64

Mode:
 case           1
site         1.0
sex         True
age          3.0
hdlngth     93.3
skullw      57.6
totlngth    89.0
taill       38.0
footlgth    73.2
earconch    44.9
eye         14.4
chest       28.0
belly       32.0
Name: 0, dtype: object

Variance:
 case        910.000000
site          5.518204
sex           0.244866
age           3.645215
hdlngth      12.768827
skullw        9.693420
totlngth     18.580836
taill         3.839712
footlgth     19.318713
earconch     16.887005
eye           1.103286
chest         4.184466
belly         7.628361
dtype: float64

Standard Deviation:
 case        30.166206
site         2.349086
sex          0.494839
age          1.909244
hdlngth      3.573349
skullw       3.113426
totlngth     4.310549
taill        1.959518
footlgth     4.395306
earconch     4.109380
eye          1.050374
chest        2.045597
belly        2.761949
dtype: float64